[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@octant-v2-core/=lib/octant-v2-core/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[rpc_endpoints]
katana = "https://rpc.katana.network"
katanaTestnet = "https://rpc.tatara.katanarpc.com"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 15